site_name: LearnOpenGL Korean

site_description: https://learnopengl.com의 한국어 번역입니다.

markdown_extensions:
  - admonition

extra_css:
  - css/style.css

nav:
  - 소개: index.md
  - GL 문서: GL-docs/
  - 목차:
    - 시작하기:
      - OpenGL: 시작하기/OpenGL.md
      - 최초의 창: 시작하기/최초의 창.md