site_name: LearnOpenGL Korean

site_description: https://learnopengl.com의 한국어 번역입니다.

theme:
  name: material

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - footnotes
  - abbr
  - pymdownx.arithmatex:
      generic: true
  
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/style.css

nav:
  - 소개: index.md
  - 시작하기:
    - OpenGL: 시작하기/OpenGL.md
    - 최초의 창: 시작하기/최초의 창.md
    - 리눅스에서의 최초의 창: 시작하기/최초의 창-리눅스.md
    - 안녕 창: 시작하기/안녕 창.md
    - 안녕 삼각형: 시작하기/안녕 삼각형.md
    - 셰이더: 시작하기/셰이더.md
    - 텍스쳐: 시작하기/텍스쳐.md
    - 변형: 시작하기/변형.md